version: 2.1

jobs:
  kolena-client-ci:
    parameters:
      python-version:
        type: string
        default: "3.9"
    docker:
      - image: cimg/python:<< parameters.python-version >>
    resource_class: small
    working_directory: "~/kolena-client"
    steps:
      - run: |
          poetry config experimental.new-installer false
          poetry config installer.max-workers 10
          poetry install --no-ansi
      - run: poetry run python3 -c 'import kolena'
      - when:
          condition:
            not:
              equal: [ "3.10", << parameters.python-version >> ]
          steps:
            - run: poetry run pre-commit run -a
      - run: poetry run pytest -vv

workflows:
  kolena-client:
    jobs:
      - kolena-client-ci:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9", "3.10"]
