# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  code_blocks: false
  headings: false
  line_length: 120
  tables: false

MD001: false
MD005: false
MD024: false
MD029: false
MD031: false
MD033: false
MD034: false
MD036: false
MD040: false
MD041: false
MD045: false
MD046: false
MD052: false
