coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

github_checks:
  annotations: false

flags:
  integration:
    paths:
      - ".*"
    carryforward: true
