site_name: Testing with Kolena
site_description: Python client for Kolena's machine learning testing platform
site_url: https://docs.kolena.io
strict: true
repo_name: kolenaIO/kolena
repo_url: https://github.com/kolenaIO/kolena
copyright: Copyright &copy; 2021-2023 Kolena
edit_uri: edit/trunk/docs/

nav:
  - Developer Guide:
      - Developer Guide: index.md
      - Quickstart: quickstart.md
      - Installing <code>kolena</code>: installing-kolena.md
      - Building a Workflow: building-a-workflow.md
      - Core Concepts:
          - Core Concepts: core-concepts/index.md
          - Workflow: core-concepts/workflow.md
          - Test Case & Test Suite: core-concepts/test-suite.md
          - Model: core-concepts/model.md
      - Advanced Usage:
          - Advanced Usage: advanced-usage/index.md
          - Connecting Cloud Storage:
              - Connecting Cloud Storage: advanced-usage/connecting-cloud-storage/index.md
              - Amazon S3: advanced-usage/connecting-cloud-storage/amazon-s3.md
              - S3-Compatible APIs: advanced-usage/connecting-cloud-storage/s3-compatible.md
              - Google Cloud Storage: advanced-usage/connecting-cloud-storage/google-cloud-storage.md
              - Azure Blob Storage: advanced-usage/connecting-cloud-storage/azure-blob-storage.md
              - HTTP Basic: advanced-usage/connecting-cloud-storage/http-basic.md
          - Packaging for Automated Evaluation: advanced-usage/packaging-for-automated-evaluation.md
          - Nesting Test Case Metrics: advanced-usage/nesting-test-case-metrics.md
          - Uploading Activation Maps: advanced-usage/uploading-activation-maps.md
          - Setting Up Natural Language Search: advanced-usage/set-up-natural-language-search.md
  - API Reference:
      - API Reference: reference/index.md
      - <code>kolena.initialize</code>: reference/initialize.md
      - <code>kolena.errors</code>: reference/errors.md
      - <code>kolena.workflow</code>:
          - <code>kolena.workflow</code>: reference/workflow/index.md
          - <code>TestSample</code>: reference/workflow/test-sample.md
          - <code>GroundTruth</code>: reference/workflow/ground-truth.md
          - <code>Inference</code>: reference/workflow/inference.md
          - <code>Evaluator</code>: reference/workflow/evaluator.md
          - <code>TestCase</code>: reference/workflow/test-case.md
          - <code>TestSuite</code>: reference/workflow/test-suite.md
          - <code>Model</code>: reference/workflow/model.md
          - <code>test</code>: reference/workflow/test-run.md
          - Utilities:
              - Annotations: reference/workflow/annotation.md
              - Assets: reference/workflow/asset.md
              - Plots: reference/workflow/plot.md
              - <code>define_workflow</code>: reference/workflow/define-workflow.md
              - <code>metrics</code>: reference/workflow/metrics.md
              - <code>ThresholdedMetrics</code>: reference/workflow/thresholded-metrics.md
              - <code>visualization</code>: reference/workflow/visualization.md
              - IO: reference/workflow/io.md
      - Pre-built Workflows:
          - Pre-built Workflows: reference/pre-built/index.md
          - Object Detection (2D): reference/pre-built/object-detection-2d.md
          - Classification: reference/pre-built/classification.md
          - Legacy Definitions:
              - Legacy Definitions: reference/legacy/index.md
              - <code>classification</code>: reference/legacy/built-in/classification.md
              - <code>detection</code>: reference/legacy/built-in/detection.md
              - <code>fr</code>: reference/legacy/built-in/fr.md
              - Base Definitions: reference/legacy/built-in/base.md
  - Metrics Glossary:
      - Metrics Glossary: metrics/index.md
      - metrics/accuracy.md
      - metrics/average-precision.md
      - metrics/averaging-methods.md
      - metrics/confusion-matrix.md
      - metrics/f1-score.md
      - metrics/fpr.md
      - metrics/precision.md
      - metrics/pr-curve.md
      - metrics/recall.md
      - metrics/roc-curve.md
      - metrics/specificity.md
      - metrics/tp-fp-fn-tn.md
      - Computer Vision:
        - metrics/geometry-matching.md
        - metrics/iou.md
      - Large Language Models:
        - metrics/contradiction-score.md
        - metrics/vectara-HEM-score.md
      - Natural Language Processing:
        - metrics/bertscore.md
        - metrics/bleu.md
        - metrics/meteor.md
        - metrics/perplexity.md
        - metrics/rouge-n.md
        - metrics/wer-cer-mer.md
  - Help & FAQ:
      - Help & FAQ: faq/index.md
  - Sign in ↗: https://app.kolena.io

theme:
  name: material
  logo: assets/images/logo-white.svg
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  font:
    text: Inter
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.follow

markdown_extensions:
  - admonition # callouts
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify # NOTE: insiders only
        kwds:
          case: lower
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - pymdownx.arithmatex:
      generic: true

watch:
  - kolena

extra_css:
  - assets/css/theme.css
  - assets/css/mkdocstrings.css

extra_javascript:
  - assets/javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  social: # render social media cards for copy+paste
    cache_dir: .cache/plugin/social/free
  search:
    lang: en
  git-revision-date-localized:
  mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.scipy.org/doc/numpy/objects.inv
        options:
          docstring_style: sphinx
          merge_init_into_class: true
          members_order: source # sort members in the order they are defined
          show_docstring_attributes: true
          show_root_toc_entry: false
          show_source: false

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kolenaIO
      name: Kolena on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kolena-ai
      name: Kolena on LinkedIn
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/kolena
    - icon: fontawesome/brands/github
      link: https://github.com/kolenaIO/kolena
      name: Kolena on GitHub
    - icon: kolena/logo
      link: https://app.kolena.io
      name: Kolena Platform
  dd_rum:
    client_token: !ENV [ DD_RUM_CLIENT_TOKEN, blank ]
    application_id: !ENV [ DD_RUM_APPLICATION_ID, blank ]
