site_name: Testing with Kolena
site_description: Python client for Kolena's machine learning (ML) testing and debugging platform
site_url: https://docs.kolena.io
strict: true
repo_name: kolenaIO/kolena
repo_url: https://github.com/kolenaIO/kolena
copyright: Copyright &copy; 2021-2023 Kolena
edit_uri: edit/trunk/docs/

nav:
  - Getting Started:
      - index.md
  - Advanced Usage:
      - advanced/index.md
  - Metrics Guide:
      - metrics-guide/index.md
  - API Reference:
      - reference/index.md
      - <code>kolena.initialize</code>: reference/initialize.md
      - <code>kolena.errors</code>: reference/errors.md
      - <code>kolena.workflow</code>:
          - reference/workflow/index.md
          - <code>TestSample</code>: reference/workflow/test_sample.md
          - <code>GroundTruth</code>: reference/workflow/ground_truth.md
          - <code>Inference</code>: reference/workflow/inference.md
          - <code>define_workflow</code>: reference/workflow/define_workflow.md
          - <code>TestCase</code>: reference/workflow/test_case.md
          - <code>TestSuite</code>: reference/workflow/test_suite.md
          - <code>Model</code>: reference/workflow/model.md
          - <code>Evaluator</code>: reference/workflow/evaluator.md
          - <code>test</code>: reference/workflow/test_run.md
          - Utilities:
              - Annotations: reference/workflow/annotation.md
              - Assets: reference/workflow/asset.md
              - <code>metrics</code>: reference/workflow/metrics.md
      - Legacy:
          - reference/legacy/index.md
          - Built-in Workflows:
              - <code>kolena.classification</code>: reference/legacy/built-in/classification.md
              - <code>kolena.detection</code>: reference/legacy/built-in/detection.md
              - <code>kolena.fr</code>: reference/legacy/built-in/fr.md
              - Base Definitions: reference/legacy/built-in/base.md
  - FAQ:
    - faq/index.md

theme:
  name: material
  logo: assets/images/logo-white.svg
  favicon: assets/images/favicon.png
  font:
    text: Inter
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to light mode"
  # NOTE: this list is duplicated in mkdocs.insiders.yml. Any changes must also be made there
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.follow

markdown_extensions:
  - admonition  # callouts
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: "¤"
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

watch:
  - kolena

extra_css:
  - css/theme.css
  - css/mkdocstrings.css

plugins:
  social:  # render social media cards for copy+paste
  search:
    lang: en
  git-revision-date-localized:
  mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_style: sphinx
          merge_init_into_class: true
          members_order: source  # sort members in the order they are defined
          show_docstring_attributes: true
          show_root_toc_entry: false
          show_source: false

extra:
  homepage: https://kolena.io
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kolenaIO
      name: Kolena on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kolena-ai
      name: Kolena on LinkedIn
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/kolena
    - icon: fontawesome/brands/github
      link: https://github.com/kolenaIO/kolena
      name: Kolena on GitHub
