# Copyright 2021-2023 Kolena Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import uuid
from typing import Dict
from typing import Tuple
from typing import Union

import pytest

from .test_evaluator_multiclass_test_sample_metrics import EXPECTED_COMPUTE_TEST_SAMPLE_METRICS
from .test_evaluator_multiclass_test_sample_metrics import TEST_CONFIGURATIONS
from .test_evaluator_multiclass_test_sample_metrics import TEST_DATA
from .test_evaluator_multiclass_test_sample_metrics import TEST_PARAMS
from kolena._experimental.object_detection import ObjectDetectionEvaluator
from kolena._experimental.object_detection.workflow import ClassMetricsPerTestCase
from kolena._experimental.object_detection.workflow import TestCase
from kolena._experimental.object_detection.workflow import TestCaseMetrics
from kolena._experimental.object_detection.workflow import TestCaseMetricsSingleClass
from tests.integration.helper import with_test_prefix


# evaluator_configuration, test_name -> test_case_metrics
EXPECTED_COMPUTE_TEST_CASE_METRICS: Dict[Tuple[str, str], Union[TestCaseMetricsSingleClass, TestCaseMetrics]] = {
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=1 and same labels and max confidence",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=1,
        TP=1,
        FN=0,
        FP=0,
        Precision=1.0,
        Recall=1.0,
        F1=1.0,
        AP=1.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0 and diff labels",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        Precision=0.0,
        Recall=0.0,
        F1=0.0,
        AP=0.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0.33 and diff labels but 0 confidence",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=0,
        TP=0,
        FN=1,
        FP=0,
        Precision=0.0,
        Recall=0.0,
        F1=0.0,
        AP=0.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0.33 and diff labels but 0.5 confidence",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        Precision=0.0,
        Recall=0.0,
        F1=0.0,
        AP=0.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0.33 and diff labels but 0.99 confidence",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        Precision=0.0,
        Recall=0.0,
        F1=0.0,
        AP=0.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0.5 and diff labels but 0 confidence",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=0,
        TP=0,
        FN=1,
        FP=0,
        Precision=0.0,
        Recall=0.0,
        F1=0.0,
        AP=0.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0.5 and diff labels but 0.5 confidence",
    ): TestCaseMetricsSingleClass(
        Objects=1,
        Inferences=1,
        TP=1,
        FN=0,
        FP=0,
        Precision=1.0,
        Recall=1.0,
        F1=1.0,
        AP=1.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "iou=0.5 and diff labels but 0.99 confidence",
    ): TestCaseMetricsSingleClass(Objects=1, Inferences=1, TP=1, FN=0, FP=0, Precision=1.0, Recall=1.0, F1=1.0, AP=1.0),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, perfect match",
    ): TestCaseMetricsSingleClass(
        Objects=4,
        Inferences=4,
        TP=4,
        FN=0,
        FP=0,
        Precision=1.0,
        Recall=1.0,
        F1=1.0,
        AP=1.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, varied iou",
    ): TestCaseMetricsSingleClass(
        Objects=4,
        Inferences=4,
        TP=3,
        FN=1,
        FP=1,
        Precision=0.75,
        Recall=0.75,
        F1=0.75,
        AP=0.5625,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, varied confidence",
    ): TestCaseMetricsSingleClass(
        Objects=4,
        Inferences=3,
        TP=3,
        FN=1,
        FP=0,
        Precision=1.0,
        Recall=0.75,
        F1=0.8571428571428571,
        AP=1.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, many inferences",
    ): TestCaseMetricsSingleClass(
        Objects=4,
        Inferences=8,
        TP=4,
        FN=0,
        FP=4,
        Precision=0.5,
        Recall=1.0,
        F1=0.6666666666666666,
        AP=0.5714285714285714,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, too few inferences",
    ): TestCaseMetricsSingleClass(
        Objects=4,
        Inferences=2,
        TP=2,
        FN=2,
        FP=0,
        Precision=1.0,
        Recall=0.5,
        F1=0.6666666666666666,
        AP=0.5,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, suboptimal infs",
    ): TestCaseMetricsSingleClass(
        Objects=4,
        Inferences=2,
        TP=1,
        FN=3,
        FP=1,
        Precision=0.5,
        Recall=0.25,
        F1=0.3333333333333333,
        AP=0.3333333333333333,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes in an image, ignored matches",
    ): TestCaseMetricsSingleClass(
        Objects=2,
        Inferences=2,
        TP=2,
        FN=0,
        FP=0,
        Precision=1.0,
        Recall=1.0,
        F1=1.0,
        AP=1.0,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "multiple bboxes test collection",
    ): TestCaseMetricsSingleClass(
        Objects=26,
        Inferences=25,
        TP=19,
        FN=7,
        FP=6,
        Precision=0.76,
        Recall=0.7307692307692307,
        F1=0.7450980392156863,
        AP=0.6282051282051283,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "large test sample",
    ): TestCaseMetricsSingleClass(
        Objects=18,
        Inferences=10,
        TP=10,
        FN=8,
        FP=0,
        Precision=1.0,
        Recall=0.5555555555555556,
        F1=0.7142857142857143,
        AP=0.8888888888888888,
    ),
    (
        "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
        "large test samples",
    ): TestCaseMetricsSingleClass(
        Objects=28,
        Inferences=14,
        TP=14,
        FN=14,
        FP=0,
        Precision=1.0,
        Recall=0.5,
        F1=0.6666666666666666,
        AP=0.7857142857142857,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=1 and same labels and max confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=1,
        FN=0,
        FP=0,
        macro_Precision=1.0,
        macro_Recall=1.0,
        macro_F1=1.0,
        mean_AP=1.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0 and diff labels",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0.33 and diff labels but 0 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=0,
        TP=0,
        FN=1,
        FP=0,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0.33 and diff labels but 0.5 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0.33 and diff labels but 0.99 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0.5 and diff labels but 0 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=0,
        TP=0,
        FN=1,
        FP=0,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0.5 and diff labels but 0.5 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "iou=0.5 and diff labels but 0.99 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, perfect match",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="d",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=4,
        Inferences=4,
        TP=4,
        FN=0,
        FP=0,
        macro_Precision=1.0,
        macro_Recall=1.0,
        macro_F1=1.0,
        mean_AP=1.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, varied iou",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=3,
                Inferences=0,
                TP=0,
                FN=3,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=1,
                TP=0,
                FN=1,
                FP=1,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=4,
        Inferences=1,
        TP=0,
        FN=4,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, varied confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=2,
                Inferences=0,
                TP=0,
                FN=2,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.1,
                Objects=2,
                Inferences=2,
                TP=2,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=4,
        Inferences=2,
        TP=2,
        FN=2,
        FP=0,
        macro_Precision=0.5,
        macro_Recall=0.5,
        macro_F1=0.5,
        mean_AP=0.5,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, many inferences",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=2,
                Inferences=2,
                TP=1,
                FN=1,
                FP=1,
                Precision=0.5,
                Recall=0.5,
                F1=0.5,
                AP=0.45,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.1,
                Objects=2,
                Inferences=2,
                TP=2,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=4,
        Inferences=4,
        TP=3,
        FN=1,
        FP=1,
        macro_Precision=0.75,
        macro_Recall=0.75,
        macro_F1=0.75,
        mean_AP=0.725,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, too few inferences",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=2,
                Inferences=0,
                TP=0,
                FN=2,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.1,
                Objects=2,
                Inferences=0,
                TP=0,
                FN=2,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=4,
        Inferences=0,
        TP=0,
        FN=4,
        FP=0,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, suboptimal infs",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=3,
                Inferences=0,
                TP=0,
                FN=3,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=4,
        Inferences=1,
        TP=0,
        FN=4,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes in an image, ignored matches",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=2,
        Inferences=1,
        TP=1,
        FN=1,
        FP=0,
        macro_Precision=0.5,
        macro_Recall=0.5,
        macro_F1=0.5,
        mean_AP=0.5,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "multiple bboxes test collection",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=7,
                Threshold=1.0,
                Objects=14,
                Inferences=3,
                TP=2,
                FN=12,
                FP=1,
                Precision=0.6666666666666666,
                Recall=0.14285714285714285,
                F1=0.23529411764705882,
                AP=0.5035714285714287,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=6,
                Threshold=0.1,
                Objects=8,
                Inferences=7,
                TP=5,
                FN=3,
                FP=2,
                Precision=0.7142857142857143,
                Recall=0.625,
                F1=0.6666666666666666,
                AP=0.44642857142857145,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=3,
                Threshold=0.1,
                Objects=3,
                Inferences=2,
                TP=2,
                FN=1,
                FP=0,
                Precision=1.0,
                Recall=0.6666666666666666,
                F1=0.8,
                AP=0.6666666666666666,
            ),
            ClassMetricsPerTestCase(
                Class="d",
                nImages=1,
                Threshold=0.1,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=26,
        Inferences=13,
        TP=10,
        FN=16,
        FP=3,
        macro_Precision=0.8452380952380952,
        macro_Recall=0.6086309523809523,
        macro_F1=0.6754901960784314,
        mean_AP=0.6541666666666667,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "large test sample",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=4,
                Inferences=1,
                TP=1,
                FN=3,
                FP=0,
                Precision=1.0,
                Recall=0.25,
                F1=0.4,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.1,
                Objects=4,
                Inferences=3,
                TP=0,
                FN=4,
                FP=3,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.1,
                Objects=10,
                Inferences=7,
                TP=7,
                FN=3,
                FP=0,
                Precision=1.0,
                Recall=0.7,
                F1=0.8235294117647058,
                AP=0.7,
            ),
        ],
        Objects=18,
        Inferences=12,
        TP=8,
        FN=10,
        FP=4,
        macro_Precision=0.6666666666666666,
        macro_Recall=0.31666666666666665,
        macro_F1=0.407843137254902,
        mean_AP=0.5666666666666667,
    ),
    (
        "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
        "large test samples",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=1.0,
                Objects=4,
                Inferences=1,
                TP=1,
                FN=3,
                FP=0,
                Precision=1.0,
                Recall=0.25,
                F1=0.4,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=2,
                Threshold=0.1,
                Objects=4,
                Inferences=6,
                TP=0,
                FN=4,
                FP=6,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.1,
                Objects=10,
                Inferences=7,
                TP=7,
                FN=3,
                FP=0,
                Precision=1.0,
                Recall=0.7,
                F1=0.8235294117647058,
                AP=0.7,
            ),
            ClassMetricsPerTestCase(
                Class="e",
                nImages=2,
                Threshold=0.1,
                Objects=10,
                Inferences=5,
                TP=4,
                FN=6,
                FP=1,
                Precision=0.8,
                Recall=0.4,
                F1=0.5333333333333333,
                AP=0.32000000000000006,
            ),
        ],
        Objects=28,
        Inferences=19,
        TP=12,
        FN=16,
        FP=7,
        macro_Precision=0.7,
        macro_Recall=0.3375,
        macro_F1=0.4392156862745098,
        mean_AP=0.505,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=1 and same labels and max confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=1,
        FN=0,
        FP=0,
        macro_Precision=1.0,
        macro_Recall=1.0,
        macro_F1=1.0,
        mean_AP=1.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0 and diff labels",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0.33 and diff labels but 0 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=0,
        TP=0,
        FN=1,
        FP=0,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0.33 and diff labels but 0.5 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0.33 and diff labels but 0.99 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0.5 and diff labels but 0 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=0,
        TP=0,
        FN=1,
        FP=0,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0.5 and diff labels but 0.5 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "iou=0.5 and diff labels but 0.99 confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=1,
        Inferences=1,
        TP=0,
        FN=1,
        FP=1,
        macro_Precision=0.0,
        macro_Recall=0.0,
        macro_F1=0.0,
        mean_AP=0.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, perfect match",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="d",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=4,
        Inferences=4,
        TP=4,
        FN=0,
        FP=0,
        macro_Precision=1.0,
        macro_Recall=1.0,
        macro_F1=1.0,
        mean_AP=1.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, varied iou",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=3,
                Inferences=3,
                TP=2,
                FN=1,
                FP=1,
                Precision=0.6666666666666666,
                Recall=0.6666666666666666,
                F1=0.6666666666666666,
                AP=0.6666666666666666,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=0,
                FN=1,
                FP=1,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=4,
        Inferences=4,
        TP=2,
        FN=2,
        FP=2,
        macro_Precision=0.3333333333333333,
        macro_Recall=0.3333333333333333,
        macro_F1=0.3333333333333333,
        mean_AP=0.3333333333333333,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, varied confidence",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=2,
                Inferences=1,
                TP=1,
                FN=1,
                FP=0,
                Precision=1.0,
                Recall=0.5,
                F1=0.6666666666666666,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.5,
                Objects=2,
                Inferences=1,
                TP=1,
                FN=1,
                FP=0,
                Precision=1.0,
                Recall=0.5,
                F1=0.6666666666666666,
                AP=1.0,
            ),
        ],
        Objects=4,
        Inferences=2,
        TP=2,
        FN=2,
        FP=0,
        macro_Precision=1.0,
        macro_Recall=0.5,
        macro_F1=0.6666666666666666,
        mean_AP=1.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, many inferences",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=2,
                Inferences=6,
                TP=2,
                FN=0,
                FP=4,
                Precision=0.3333333333333333,
                Recall=1.0,
                F1=0.5,
                AP=0.45,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.5,
                Objects=2,
                Inferences=2,
                TP=2,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=4,
        Inferences=8,
        TP=4,
        FN=0,
        FP=4,
        macro_Precision=0.6666666666666666,
        macro_Recall=1.0,
        macro_F1=0.75,
        mean_AP=0.725,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, too few inferences",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=2,
                Inferences=1,
                TP=1,
                FN=1,
                FP=0,
                Precision=1.0,
                Recall=0.5,
                F1=0.6666666666666666,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.5,
                Objects=2,
                Inferences=0,
                TP=0,
                FN=2,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=4,
        Inferences=1,
        TP=1,
        FN=3,
        FP=0,
        macro_Precision=0.5,
        macro_Recall=0.25,
        macro_F1=0.3333333333333333,
        mean_AP=0.5,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, suboptimal infs",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=3,
                Inferences=1,
                TP=1,
                FN=2,
                FP=0,
                Precision=1.0,
                Recall=0.3333333333333333,
                F1=0.5,
                AP=0.6666666666666666,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=0,
                TP=0,
                FN=1,
                FP=0,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
        ],
        Objects=4,
        Inferences=2,
        TP=1,
        FN=3,
        FP=1,
        macro_Precision=0.5,
        macro_Recall=0.16666666666666666,
        macro_F1=0.25,
        mean_AP=0.3333333333333333,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes in an image, ignored matches",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=2,
        Inferences=2,
        TP=2,
        FN=0,
        FP=0,
        macro_Precision=1.0,
        macro_Recall=1.0,
        macro_F1=1.0,
        mean_AP=1.0,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "large test sample",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=4,
                Inferences=4,
                TP=4,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=1,
                Threshold=0.5,
                Objects=4,
                Inferences=1,
                TP=0,
                FN=4,
                FP=1,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.5,
                Objects=10,
                Inferences=3,
                TP=3,
                FN=7,
                FP=0,
                Precision=1.0,
                Recall=0.3,
                F1=0.4615384615384615,
                AP=0.8,
            ),
        ],
        Objects=18,
        Inferences=9,
        TP=7,
        FN=11,
        FP=2,
        macro_Precision=0.6666666666666666,
        macro_Recall=0.43333333333333335,
        macro_F1=0.48717948717948717,
        mean_AP=0.6,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "large test samples",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=1,
                Threshold=0.5,
                Objects=4,
                Inferences=4,
                TP=4,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=2,
                Threshold=0.5,
                Objects=4,
                Inferences=4,
                TP=0,
                FN=4,
                FP=4,
                Precision=0.0,
                Recall=0.0,
                F1=0.0,
                AP=0.0,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=1,
                Threshold=0.5,
                Objects=10,
                Inferences=3,
                TP=3,
                FN=7,
                FP=0,
                Precision=1.0,
                Recall=0.3,
                F1=0.4615384615384615,
                AP=0.8,
            ),
            ClassMetricsPerTestCase(
                Class="e",
                nImages=2,
                Threshold=0.5,
                Objects=10,
                Inferences=4,
                TP=3,
                FN=7,
                FP=1,
                Precision=0.75,
                Recall=0.3,
                F1=0.4285714285714285,
                AP=0.4166666666666667,
            ),
        ],
        Objects=28,
        Inferences=15,
        TP=10,
        FN=18,
        FP=5,
        macro_Precision=0.6875,
        macro_Recall=0.4,
        macro_F1=0.4725274725274725,
        mean_AP=0.5541666666666667,
    ),
    (
        "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
        "multiple bboxes test collection",
    ): TestCaseMetrics(
        PerClass=[
            ClassMetricsPerTestCase(
                Class="a",
                nImages=7,
                Threshold=0.5,
                Objects=14,
                Inferences=14,
                TP=9,
                FN=5,
                FP=5,
                Precision=0.6428571428571429,
                Recall=0.6428571428571429,
                F1=0.6428571428571429,
                AP=0.6144957983193277,
            ),
            ClassMetricsPerTestCase(
                Class="b",
                nImages=6,
                Threshold=0.5,
                Objects=8,
                Inferences=6,
                TP=4,
                FN=4,
                FP=2,
                Precision=0.6666666666666666,
                Recall=0.5,
                F1=0.5714285714285715,
                AP=0.44642857142857145,
            ),
            ClassMetricsPerTestCase(
                Class="c",
                nImages=3,
                Threshold=0.5,
                Objects=3,
                Inferences=2,
                TP=2,
                FN=1,
                FP=0,
                Precision=1.0,
                Recall=0.6666666666666666,
                F1=0.8,
                AP=0.6666666666666666,
            ),
            ClassMetricsPerTestCase(
                Class="d",
                nImages=1,
                Threshold=0.5,
                Objects=1,
                Inferences=1,
                TP=1,
                FN=0,
                FP=0,
                Precision=1.0,
                Recall=1.0,
                F1=1.0,
                AP=1.0,
            ),
        ],
        Objects=26,
        Inferences=23,
        TP=16,
        FN=10,
        FP=7,
        macro_Precision=0.8273809523809523,
        macro_Recall=0.7023809523809523,
        macro_F1=0.7535714285714286,
        mean_AP=0.6818977591036415,
    ),
}


@pytest.mark.metrics
@pytest.mark.parametrize(
    "config_name, test_name",
    TEST_PARAMS,
)
def test__prebuilt__object__detection__multiclass__compute__test__case__metrics(
    config_name: str,
    test_name: str,
) -> None:
    config = TEST_CONFIGURATIONS[config_name]
    eval = ObjectDetectionEvaluator(configurations=[config])
    random_test_case_name = with_test_prefix("test_evaluator_multiclass") + str(uuid.uuid4())
    test_case = TestCase(random_test_case_name, reset=True)
    eval.compute_test_sample_metrics(
        test_case=test_case,
        inferences=TEST_DATA[test_name],
        configuration=config,
    )

    result = eval.compute_test_case_metrics(
        test_case=test_case,
        inferences=TEST_DATA[test_name],
        metrics=[metric for _, metric in EXPECTED_COMPUTE_TEST_SAMPLE_METRICS[config_name, test_name]],
        configuration=config,
    )

    expected = EXPECTED_COMPUTE_TEST_CASE_METRICS[config_name, test_name]
    print(config_name, test_name)
    print(result)
    assert expected == result


@pytest.mark.metrics
@pytest.mark.parametrize(
    "config_name, expected",
    [
        (
            "Threshold: Fixed(0.3), IoU: 0.3, confidence ≥ 0.0",
            TestCaseMetricsSingleClass(
                Objects=106,
                Inferences=80,
                TP=65,
                FN=41,
                FP=15,
                Precision=0.8125,
                Recall=0.6132075471698113,
                F1=0.6989247311827956,
                AP=0.6698074304609998,
            ),
        ),
        (
            "Threshold: Fixed(0.5) by class, IoU: 0.5, confidence ≥ 0.0",
            TestCaseMetrics(
                PerClass=[
                    ClassMetricsPerTestCase(
                        Class="a",
                        nImages=24,
                        Threshold=0.5,
                        Objects=44,
                        Inferences=37,
                        TP=27,
                        FN=17,
                        FP=10,
                        Precision=0.7297297297297297,
                        Recall=0.6136363636363636,
                        F1=0.6666666666666666,
                        AP=0.5887789096034338,
                    ),
                    ClassMetricsPerTestCase(
                        Class="b",
                        nImages=22,
                        Threshold=0.5,
                        Objects=24,
                        Inferences=22,
                        TP=8,
                        FN=16,
                        FP=14,
                        Precision=0.36363636363636365,
                        Recall=0.3333333333333333,
                        F1=0.34782608695652173,
                        AP=0.1765873015873016,
                    ),
                    ClassMetricsPerTestCase(
                        Class="c",
                        nImages=8,
                        Threshold=0.5,
                        Objects=26,
                        Inferences=10,
                        TP=10,
                        FN=16,
                        FP=0,
                        Precision=1.0,
                        Recall=0.38461538461538464,
                        F1=0.5555555555555556,
                        AP=0.7692307692307693,
                    ),
                    ClassMetricsPerTestCase(
                        Class="d",
                        nImages=2,
                        Threshold=0.5,
                        Objects=2,
                        Inferences=2,
                        TP=2,
                        FN=0,
                        FP=0,
                        Precision=1.0,
                        Recall=1.0,
                        F1=1.0,
                        AP=1.0,
                    ),
                    ClassMetricsPerTestCase(
                        Class="e",
                        nImages=3,
                        Threshold=0.5,
                        Objects=10,
                        Inferences=5,
                        TP=3,
                        FN=7,
                        FP=2,
                        Precision=0.6,
                        Recall=0.3,
                        F1=0.4,
                        AP=0.35714285714285715,
                    ),
                ],
                Objects=106,
                Inferences=76,
                TP=50,
                FN=56,
                FP=26,
                macro_Precision=0.7386732186732187,
                macro_Recall=0.5263170163170162,
                macro_F1=0.5940096618357488,
                mean_AP=0.5783479675128723,
            ),
        ),
        (
            "Threshold: F1-Optimal by class, IoU: 0.5, confidence ≥ 0.1",
            TestCaseMetrics(
                PerClass=[
                    ClassMetricsPerTestCase(
                        Class="a",
                        nImages=24,
                        Threshold=1.0,
                        Objects=44,
                        Inferences=9,
                        TP=7,
                        FN=37,
                        FP=2,
                        Precision=0.7777777777777778,
                        Recall=0.1590909090909091,
                        F1=0.2641509433962264,
                        AP=0.5159461750370841,
                    ),
                    ClassMetricsPerTestCase(
                        Class="b",
                        nImages=20,
                        Threshold=0.1,
                        Objects=24,
                        Inferences=28,
                        TP=10,
                        FN=14,
                        FP=18,
                        Precision=0.35714285714285715,
                        Recall=0.4166666666666667,
                        F1=0.3846153846153846,
                        AP=0.1765873015873016,
                    ),
                    ClassMetricsPerTestCase(
                        Class="c",
                        nImages=8,
                        Threshold=0.1,
                        Objects=26,
                        Inferences=18,
                        TP=18,
                        FN=8,
                        FP=0,
                        Precision=1.0,
                        Recall=0.6923076923076923,
                        F1=0.8181818181818181,
                        AP=0.6923076923076923,
                    ),
                    ClassMetricsPerTestCase(
                        Class="d",
                        nImages=2,
                        Threshold=0.1,
                        Objects=2,
                        Inferences=2,
                        TP=2,
                        FN=0,
                        FP=0,
                        Precision=1.0,
                        Recall=1.0,
                        F1=1.0,
                        AP=1.0,
                    ),
                    ClassMetricsPerTestCase(
                        Class="e",
                        nImages=3,
                        Threshold=0.1,
                        Objects=10,
                        Inferences=6,
                        TP=4,
                        FN=6,
                        FP=2,
                        Precision=0.6666666666666666,
                        Recall=0.4,
                        F1=0.5,
                        AP=0.26666666666666666,
                    ),
                ],
                Objects=106,
                Inferences=63,
                TP=41,
                FN=65,
                FP=22,
                macro_Precision=0.7603174603174603,
                macro_Recall=0.5336130536130537,
                macro_F1=0.5933896292386859,
                mean_AP=0.5303015671197489,
            ),
        ),
    ],
)
def test__prebuilt__object__detection__multiclass__compute__test__case__metrics__all(
    config_name: str,
    expected: TestCaseMetricsSingleClass,
) -> None:
    config = TEST_CONFIGURATIONS[config_name]
    eval = ObjectDetectionEvaluator(configurations=[config])
    random_test_case_name = with_test_prefix("test_evaluator_multiclass") + str(uuid.uuid4())
    test_case = TestCase(random_test_case_name, reset=True)
    eval.compute_test_sample_metrics(
        test_case=test_case,
        inferences=[ts_gt_inf for _, data in TEST_DATA.items() for ts_gt_inf in data],
        configuration=config,
    )
    result = eval.compute_test_case_metrics(
        test_case=test_case,
        inferences=[ts_gt_inf for _, data in TEST_DATA.items() for ts_gt_inf in data],
        metrics=[
            metric
            for config_test, metrics in EXPECTED_COMPUTE_TEST_SAMPLE_METRICS.items()
            for _, metric in metrics
            if config_test[0] == config_name
        ],
        configuration=config,
    )
    print(config_name)
    print(result)
    assert expected == result
